# Generated by Django 5.1.1 on 2024-09-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qera', '0005_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
    ]
